pipeline { 
    agent any 
    environment { 
        TF_WORKSPACE = 'Day-5' 
        AWS_ACCESS_KEY_ID = credentials('aws-access-key-id') 
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY') 
    }

    stages {

        stage('Cleanup Workspace') {
            steps { deleteDir() // This step deletes the contents of the workspace
                  
            }
        }
        stage('Clone Repository') {
            steps {
                git 'https://github.com/pravallikagithubrit/terraform-zero-to-hero.git'
            }
        }
        stage('Terraform Init') {
            steps {
                dir('Day-5') {
                    sh 'terraform init'
                }
            }
        }
        stage('Terraform Plan') {
            steps {
                dir('Day-5') {
                    sh 'terraform plan'
                }
            }
        }
        stage('Terraform Apply') {
            steps {
                dir('Day-5') {
                    sh 'terraform apply -auto-approve'
                }
            }
        }
        stage('Test Application') { 
            steps {
                sh 'curl http://54.81.134.133:5000'
            }
        }
    }
    post {
        always {
            echo 'Pipeline completed'
        }
        failure {
            echo 'Pipeline failed'
        }
    }
}
